steps:
# Step 1: Install zip and create archive
- name: 'ubuntu'
  entrypoint: bash
  args:
    - -c
    - |
      apt-get update
      apt-get install -y zip
      zip -r code.zip app/

# Step 2: Upload to GCS
- name: 'gcr.io/cloud-builders/gsutil'
  args:
    - cp
    - code.zip
    - gs://etl-pyspark-bucket/code.zip

options:
  logging: CLOUD_LOGGING_ONLY