steps:
# Zip
- name: 'ubuntu'
  entrypoint: bash
  args:
    - -c
    - |
      apt-get update && apt-get install -y zip
      zip -r code.zip app/

# Upload zip
- name: 'gcr.io/cloud-builders/gsutil'
  args:
    - cp
    - code.zip
    - gs://etl-pyspark-bucket/code.zip

# 🔥 Upload main.py (NEW)
- name: 'gcr.io/cloud-builders/gsutil'
  args:
    - cp
    - app/main.py
    - gs://etl-pyspark-bucket/main.py

# Run job
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - dataproc
    - jobs
    - submit
    - pyspark
    - gs://etl-pyspark-bucket/main.py
    - --cluster=pyspark-cluster
    - --region=us-east1
    - --py-files=gs://etl-pyspark-bucket/code.zip

options:
  logging: CLOUD_LOGGING_ONLY