steps:
# 1) Zip your app
- name: 'ubuntu'
  entrypoint: bash
  args:
    - -c
    - |
      apt-get update && apt-get install -y zip
      zip -r code.zip app/

# 2) Upload to GCS
- name: 'gcr.io/cloud-builders/gsutil'
  args:
    - cp
    - code.zip
    - gs://etl-pyspark-bucket/code.zip

# 3) Submit Dataproc job 🚀
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - dataproc
    - jobs
    - submit
    - pyspark
    - gs://etl-pyspark-bucket/main.py
    - --cluster=pyspark-cluster          # 🔁 change to your cluster name
    - --region=us-east1                 # 🔁 your region
    - --py-files=gs://etl-pyspark-bucket/code.zip

options:
  logging: CLOUD_LOGGING_ONLY